[package]
name = "sound"
version = "0.1.0"
edition = "2021"

[lib]
name = "sound"
path = "src/lib.rs"

[[bin]]
name = "sound"
path = "src/main.rs"

[dependencies]
rodio = "0.21.1"
clap = { version = "4.5.42", features = ["derive"] }
crossterm = "0.29.0"